# Change these first
owner: flow-finance # Your GitHub organization or username, where this repository lives
repo: lighthouse # The name of this repository

sites:
  - name: FlowFi.com
    url: https://www.flowfi.com
  - name: FlowFi App
    url: https://app.flowfi.com
  - name: Workbench
    url: https://alpha.workbench.flowfi.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /lighthouse
  logoUrl: https://raw.githubusercontent.com/flow-finance/lighthouse/master/assets/flowfi-logo.svg
  name: Lighthouse
  introTitle: "**System Status**"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  css: "body { background-color: #F7F9FA; } nav img { width: 66px; }"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
